### ISSUE TITLE
How to use react-fontawesome for css like before after content

### ISSUE THREAD

**Issue by bocanhcam** [FortAwesome/react-fontawesome#372]
I excepted this to be work but it doesn't. I don't see anything in the docs so please give some help
```css
@import "~@fortawesome/fontawesome-svg-core/styles.css";

.icon{
    content: "\f00c ";
    position: absolute;
    font-family: 'Font Awesome 5 Free';
    right: 15px;
    top: 9px;
    font-size: 20px;
    color: #7ebc4c;
    position: absolute;
}
```
