### ISSUE TITLE
Using Font Awesome Icons as Pseudo-elements in Gatsby

### ISSUE THREAD

**Issue by rsapkf** [FortAwesome/react-fontawesome#416]
I was able to successfully install the react library and use the icons in my components as explained in the [docs](https://fontawesome.com/how-to-use/on-the-web/using-with/react) but I have a global scss file that uses FontAwesome icons as pseudo-elements to target external links in the site. Here is a snippet from my scss:

```scss
@import url("https://use.fontawesome.com/releases/v5.7.0/css/all.css");

a {
	  &:not([href^="/"]):not([href^="#"]):not([href*="mozilla.org"])::after {
	      content: "\f35d"; // external link icon
	      font-family: "Font Awesome 5 Free";
	      font-weight: 900;
	    }
	  
	  &::after {
	    font-family: "Font Awesome 5 Brands";
	    font-weight: 400;
	    color: rgb(85, 78, 78);
	    font-size: 0.65rem;
	    padding: 0.15rem;
	    position: relative;
	    bottom: 0.2rem;
	  }

	  &[href*="mozilla.org"]::after {
	      content: "\f269";
	    }

	  // rules for other brand icons
}
```

I have many rules for different brands (github, apple, hackernews, etc) to display specific icons for specific sites. The css file is [here](https://github.com/rsapkf/rsapkf.xyz/blob/master/src/styles/index.scss#L45).

I am also using icons as pseudo-elements in my scss modules (e.g. in NavBar component to display angle-down icon in dropdowm)

If I remove the import statement in the beginning, this stops working. This works fine on my laptop since I have Font Awesome for the desktop installed but obviously doesn't work on the ones where I don't have desktop icons installed.

What is the best way to solve the issue? Should I revert back to using the import and download the entire css file? I have tried copying Unicode Glyphs directly in my css and downloading the individual SVGs and using those but these solutions defy the purpose of using the library and aren't as elegant.
